---
title: "Robust HMMs"
output: html_notebook
---

Code to generate state vectors
```{r}
source("helper.R")
```

Generate observations from a (1 - w) * normal + w * student_t
```{r}
mus <- c(1, 8)
sigmas <- c(1, 1)
dfs <- c(3, 3)
K <- 2
m_transition_probs <- matrix(c(0.9, 0.1, 0.1, 0.9), ncol = 2)

n_steps <- 1000
df <- simulate_hmm(n_steps, 1, m_transition_probs, 0, mus, sigmas, dfs)

df %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=state))
```

```{r}
g <- df %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point() +
  xlab("Time") +
  ylab(latex2exp::TeX("$\\Y_t"))

ggsave("../figures/simulated_normal.pdf", g, width = 6,
       height = 3)
```


Fit models
```{r}
model_normal <- stan_model("hmm.stan")
model_student_t <- stan_model("hmm_student_t.stan")
model_robust <- stan_model("hmm_beta_divergence.stan")

data_stan <- list(
  N=nrow(df),
  dist=df$obs,
  K=2,
  beta=0.1
  )

n_opt <- 2
fit_normal <- optimise_repeat(n_opt, model_normal, data=data_stan)
fit_student_t <- optimise_repeat(n_opt, model_student_t, data=data_stan)
fit_robust <- optimise_repeat(n_opt, model_robust, data=data_stan)

df <- df %>% 
  mutate(normal=fit_normal$par$state,
         student_t=fit_student_t$par$state,
         robust=fit_robust$par$state) %>% 
  mutate(normal=as.factor(normal),
         student_t=as.factor(student_t),
         robust=as.factor(robust))

df %>% 
  pivot_longer(-c("time", "obs")) %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=value)) +
  facet_wrap(~name)
```

```{r}
# some issue with algo for t=1
df$normal[1] <- 1

g <- df %>%
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=normal)) +
  xlab("Time") +
  ylab(latex2exp::TeX("$\\Y_t")) +
  scale_color_brewer("State", palette = "Dark2")

ggsave("../figures/simulated_normal_state.pdf", g, width = 6,
       height = 3)
```

Now corrupt data
```{r}
dfs <- c(1.5, 1.5)
df <- simulate_hmm(n_steps, 1, m_transition_probs, 0.2, mus, sigmas, dfs)

g <- df %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=state)) +
  xlab("Time") +
  ylab(latex2exp::TeX("$\\Y_t")) +
  scale_color_brewer("State", palette = "Dark2")
g
```

```{r}
data_stan <- list(
  N=nrow(df),
  dist=df$obs,
  K=2,
  beta=0.1
  )

n_opt <- 2
fit_normal <- optimise_repeat(n_opt, model_normal, data=data_stan)
fit_student_t <- optimise_repeat(n_opt, model_student_t, data=data_stan)
fit_robust <- optimise_repeat(n_opt, model_robust, data=data_stan)

df <- df %>% 
  mutate(normal=fit_normal$par$state,
         student_t=fit_student_t$par$state,
         robust=fit_robust$par$state) %>% 
  mutate(normal=as.factor(normal),
         student_t=as.factor(student_t),
         robust=as.factor(robust))
```

```{r}
# some issue with algo for t=1
df$normal[1] <- 1

g <- df %>%
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=normal)) +
  xlab("Time") +
  ylab(latex2exp::TeX("$\\Y_t")) +
  scale_color_brewer("State", palette = "Dark2")
```

With 3 states
```{r}
data_stan <- list(
  N=nrow(df),
  dist=df$obs,
  K=3,
  beta=0.1
  )

n_opt <- 2
fit_normal <- optimise_repeat(n_opt, model_normal, data=data_stan)

df <- df %>% 
  mutate(normal=fit_normal$par$state,
         student_t=fit_student_t$par$state,
         robust=fit_robust$par$state) %>% 
  mutate(normal=as.factor(normal),
         student_t=as.factor(student_t),
         robust=as.factor(robust))

# some issue with algo for t=1
df$normal[1] <- 1

g <- df %>%
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=normal)) +
  xlab("Time") +
  ylab(latex2exp::TeX("$\\Y_t")) +
  scale_color_brewer("State", palette = "Dark2")
g
```



How many states?
```{r}
find_optimal_k <- function(n_opt, base_parameters, model, data_stan, ks=2:4) {
  bics <- vector(length = length(ks))
  for(i in seq_along(bics)){
    K <- ks[i]
    data_stan$K <- K 
    fit <- optimise_repeat(n_opt, model, data=data_stan)
    log_like <- fit$par$log_p;
    num_parameters <- K * base_parameters + K * (K - 1)
    bics[i] <- 2 * log_like - num_parameters * log(data_stan$N)
  }
  bics
}

ks <- seq(2, 4, 1)
bics <- find_optimal_k(5, 3, model_normal, data_stan, ks=ks)
plot(ks, bics)
```


Look at purity of state estimation
```{r}
mean(df$state==df$normal)
mean(df$state==df$robust)
mean(df$state==df$student_t)
```

Try fitting a DP to fake HMM data
```{r}
n_steps <- 2000
df <- simulate_hmm(n_steps, 1, m_transition_probs, 0, mus, sigmas, dfs)

df %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=state))

library(dirichletprocess)
dp <- DirichletProcessGaussian(scale(df$obs), g0Priors = c(0, 1, 2, 1),
                               alphaPriors = c(0.1, 4))
n_iter <- 400
dp_1 <- Fit(dp, n_iter)
dp_2 <- Fit(dp, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()

dp_1$numberClusters
dp_2$numberClusters
dp_1$alpha

df %>% 
  mutate(cluster=dp_2$clusterLabels) %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=cluster))
```

```{r}
dfs <- c(3, 3)
df <- simulate_hmm(n_steps, 1, m_transition_probs, 0.2, mus, sigmas, dfs)

df %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=state))

dp <- DirichletProcessGaussian(scale(df$obs), g0Priors = c(0, 1, 2, 1),
                               alphaPriors = c(0.1, 4))
n_iter <- 400
dp_1 <- Fit(dp, n_iter)
dp_2 <- Fit(dp, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()

dp_1$numberClusters
dp_2$numberClusters
dp_1$alpha

df %>% 
  mutate(cluster=dp_2$clusterLabels) %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=cluster))
```
Try tempering the likelihood
```{r}
Likelihood.tempered <- function(mdobj, x, theta){
  beta <- 1
  val1 <- 1 / beta * dnorm(x, theta[[1]], theta[[2]])^beta
  # val2 <- (1 / (beta + 1)) * integrate(function(x) dnorm(x, theta[[1]], theta[[2]])^(beta + 1), -20, 20)$value
  as.numeric(val1)
}
PriorDraw.tempered <- function(mdobj, n=1){
  theta <- list()
  theta[[1]] = array(rnorm(n, mdobj$priorParameters[1], mdobj$priorParameters[2]), dim=c(1, 1, n))
  theta[[2]] = array(rexp(n, mdobj$priorParameters[3]), dim=c(1, 1, n))
  theta
}
PriorDensity.tempered <- function(mdobj, theta){
  priorParameters <- mdobj$priorParameters
  thetaDensity <- dnorm(theta[[1]], priorParameters[1], priorParameters[2])
  thetaDensity <- thetaDensity * dexp(theta[[2]], priorParameters[3])
  as.numeric(thetaDensity)
}
MhParameterProposal.tempered <- function(mdobj, oldParams){
  mhStepSize <- mdobj$mhStepSize
  newParams <- oldParams
  newParams[[1]] <- oldParams[[1]] + mhStepSize[1]*rnorm(1)
  newParams[[2]] <- abs(oldParams[[2]] + mhStepSize[2]*rnorm(1))
  newParams
}
temperedMd <- MixingDistribution(distribution = "tempered",
  priorParameters = c(0, 5, 0.01),
  conjugate = "nonconjugate",
  mhStepSize = c(1, 0.1)
)
dp <- DirichletProcessCreate(scale(df$obs), temperedMd)
dp <- Initialise(dp, numInitialClusters = 3)
dp <- Fit(dp, 200)

df %>% 
  mutate(cluster=dp$clusterLabels) %>% 
  ggplot(aes(x=time, y=obs)) +
  geom_line() +
  geom_point(aes(colour=cluster))
```



Try fitting DP to fake 2 mean data
```{r}
n <- 200
x <- vector(length = n)
for(i in seq_along(x)) {
  u <- runif(1)
  if(u > 0.5)
    x[i] <- rnorm(1, 0, 1)
  else
    x[i] <- rnorm(1, 10, 1)
}
x <- scale(x)

dp <- DirichletProcessGaussian(x, g0Priors = c(0, 1, 2, 1))
n_iter <- 1000
dp_1 <- Fit(dp, n_iter)
dp_2 <- Fit(dp, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()

hist(n_clusters_2)
```



# Real data
```{r}
df <- read.csv("../../../../Downloads/doi_10.5061_dryad.dr7sqv9v9__v3/ElephantsData_ano.csv",sep=";")

df %>% 
  filter(id==1) %>% 
  mutate(time=seq_along(id)) %>% 
  ggplot(aes(x=time, y=Dist)) +
  geom_line()
```

Fit DP to data
```{r}
library(dirichletprocess)

df_1 <- df %>% 
  filter(id==1) %>% 
  slice(1:200)
dp <- DirichletProcessGaussian(df_1$Dist,
                               alphaPriors = c(0.01, 4))
n_iter <- 400
dp_1 <- Fit(dp, n_iter)
dp_2 <- Fit(dp, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()

dp_1$numberClusters
dp_2$numberClusters
dp_1$alpha
```

Try with more angle data too
```{r}
df_s <- df %>% 
  filter(id==1) %>% 
  slice(1:200) %>% 
  select(Dist, Angle) %>% 
  scale()

df_s %>% 
  as.data.frame() %>% 
  mutate(time=seq_along(Dist)) %>% 
  pivot_longer(-time) %>% 
  ggplot(aes(x=time, y=value)) +
  geom_line() +
  facet_wrap(~name)

dp_1 <- DirichletProcessMvnormal(df_s, numInitialClusters = 2, alphaPriors = c(0.001, 4))
dp_2 <- DirichletProcessMvnormal(df_s, numInitialClusters = 2, alphaPriors = c(0.001, 4))
n_iter <- 200
dp_1 <- Fit(dp_1, n_iter)
dp_2 <- Fit(dp_2, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()
```
Look at clusters
```{r}
plot(dp_1)

cluster_labels <- dp_2$clusterLabels
df_s %>% 
  as.data.frame() %>% 
  mutate(cluster=cluster_labels)
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()
```

# DPM on Mathematica HMM data
```{r}
x <- read.csv("../data/hmm_test.csv", header = FALSE)

x <- x %>% 
  slice(1:nrow(x))

dp_1 <- DirichletProcessGaussian(
  scale(x$V2), alphaPriors = c(4, 4))
dp_2 <- DirichletProcessGaussian(
  scale(x$V2), alphaPriors = c(4, 4))
dp_1 <- Initialise(dp_1, numInitialClusters = 1)
dp_2 <- Initialise(dp_2, numInitialClusters = 10)

n_iter <- 2000
dp_1 <- Fit(dp, n_iter)
dp_2 <- Fit(dp, n_iter)

n_clusters_1 <- map_dbl(dp_1$labelsChain, ~max(.))
n_clusters_2 <- map_dbl(dp_2$labelsChain, ~max(.))

tibble(n1=n_clusters_1, n2=n_clusters_2) %>% 
  mutate(iter=seq_along(n1)) %>% 
  pivot_longer(-iter) %>% 
  ggplot(aes(x=iter, y=value, colour=name)) +
  geom_line()

dp_1$numberClusters
dp_2$numberClusters

hist(n_clusters_1)

# find MAP
m_1 <- which.max(dp_1$likelihoodChain)
n_clusters_1[m_1]
m_2 <- which.max(dp_2$likelihoodChain)
n_clusters_2[m_2]
```





